/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BarterItemSchema extends BaseModel {
  static $columns = ['barterId', 'createdAt', 'id', 'kind', 'productId', 'productName', 'quantity', 'unit', 'unitValue', 'updatedAt'] as const
  $columns = BarterItemSchema.$columns
  @column()
  declare barterId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare productId: number | null
  @column()
  declare productName: string
  @column()
  declare quantity: number
  @column()
  declare unit: string
  @column()
  declare unitValue: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BarterSchema extends BaseModel {
  static $columns = ['adminNote', 'code', 'createdAt', 'id', 'producerId', 'producerName', 'reviewedAt', 'reviewedBy', 'reviewedById', 'sellerBranch', 'sellerId', 'sellerName', 'status', 'updatedAt'] as const
  $columns = BarterSchema.$columns
  @column()
  declare adminNote: string | null
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare producerId: number | null
  @column()
  declare producerName: string
  @column.dateTime()
  declare reviewedAt: DateTime | null
  @column()
  declare reviewedBy: string | null
  @column()
  declare reviewedById: number | null
  @column()
  declare sellerBranch: string
  @column()
  declare sellerId: number | null
  @column()
  declare sellerName: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InputCategorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'ruleType', 'ruleValue', 'updatedAt'] as const
  $columns = InputCategorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ruleType: string
  @column()
  declare ruleValue: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PriceHistoryEntrySchema extends BaseModel {
  static $columns = ['changedAt', 'changedBy', 'changedById', 'createdAt', 'id', 'price', 'productId', 'updatedAt'] as const
  $columns = PriceHistoryEntrySchema.$columns
  @column.dateTime()
  declare changedAt: DateTime
  @column()
  declare changedBy: string
  @column()
  declare changedById: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare price: number
  @column()
  declare productId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProducerSchema extends BaseModel {
  static $columns = ['areaHa', 'city', 'createdAt', 'document', 'farmName', 'id', 'name', 'phone', 'sellerId', 'updatedAt'] as const
  $columns = ProducerSchema.$columns
  @column()
  declare areaHa: number
  @column()
  declare city: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare document: string
  @column()
  declare farmName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare sellerId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['categoryId', 'createdAt', 'currentPrice', 'id', 'name', 'requiredPerHa', 'type', 'unit', 'updatedAt'] as const
  $columns = ProductSchema.$columns
  @column()
  declare categoryId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentPrice: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare requiredPerHa: number
  @column()
  declare type: string
  @column()
  declare unit: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['branch', 'createdAt', 'email', 'fullName', 'id', 'password', 'phone', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare branch: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
