/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Barters: () => import('#controllers/barters_controller'),
  Categories: () => import('#controllers/categories_controller'),
  Producers: () => import('#controllers/producers_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Sellers: () => import('#controllers/sellers_controller'),
}
