/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type BarterItemTransformer from '#transformers/barter_item_transformer'
import type BarterTransformer from '#transformers/barter_transformer'
import type InputCategoryTransformer from '#transformers/input_category_transformer'
import type PriceHistoryEntryTransformer from '#transformers/price_history_entry_transformer'
import type ProducerTransformer from '#transformers/producer_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type BarterItem = InferData<BarterItemTransformer>
  export namespace BarterItem {
    export type Variants = InferVariants<BarterItemTransformer>
  }
  export type Barter = InferData<BarterTransformer>
  export namespace Barter {
    export type Variants = InferVariants<BarterTransformer>
  }
  export type InputCategory = InferData<InputCategoryTransformer>
  export namespace InputCategory {
    export type Variants = InferVariants<InputCategoryTransformer>
  }
  export type PriceHistoryEntry = InferData<PriceHistoryEntryTransformer>
  export namespace PriceHistoryEntry {
    export type Variants = InferVariants<PriceHistoryEntryTransformer>
  }
  export type Producer = InferData<ProducerTransformer>
  export namespace Producer {
    export type Variants = InferVariants<ProducerTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
